import type { Metadata, Viewport } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Instrument_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Mono is the interface font here, not just the code font — see the direction
// note at the top of globals.css. The sans is used in exactly one place, the
// problem statement, where running monospace gets tiring.
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

const title = "thirty70 — Collaborative LeetCode";
const description =
  "Solve LeetCode problems together with friends in real-time.";

export const metadata: Metadata = {
  // Without this, the og:image generated by app/opengraph-image.tsx has no
  // origin to be made absolute against — Next warns at build time and social
  // scrapers, which don't resolve relative image URLs, drop the card.
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_APP_URL ?? "https://thirty70.vercel.app"
  ),
  title,
  description,
  openGraph: { title, description, type: "website" },
  // Twitter falls back to og: tags for everything except the card type, and
  // the type is what decides between a thumbnail and a full-width image.
  twitter: { card: "summary_large_image", title, description },
};

// Paints the mobile browser chrome to match the page. Two entries rather than
// one: the value is picked by media query, so it tracks the OS setting the
// same way the CSS fallback does.
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbfbf9" },
    { media: "(prefers-color-scheme: dark)", color: "#141311" },
  ],
};

// Runs before first paint, so the page never renders in one theme and then
// snaps to the other. It has to be inline and synchronous in <head> for that
// to hold — a component effect runs after the first paint, which is precisely
// the flash. Reads the same key and falls back to the same OS query as
// hooks/useTheme.ts; keep the two in step.
const THEME_BOOT_SCRIPT = `
(function () {
  try {
    var stored = localStorage.getItem("theme");
    // A viewer who has never chosen follows their OS, so a missing key is
    // treated the same as an explicit "system". Only "light" opts out of a
    // dark machine. (No backticks in here — this whole script is a template
    // literal.)
    var dark = stored === "dark" ||
      (stored !== "light" && window.matchMedia("(prefers-color-scheme: dark)").matches);
    document.documentElement.setAttribute("data-theme", dark ? "dark" : "light");
  } catch (e) {
    // Storage blocked. The CSS still follows prefers-color-scheme on its own
    // when no data-theme is stamped, so leaving the attribute off is correct.
  }
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      {/* The boot script sets data-theme before React hydrates, so the server
          markup and the client markup differ on <html> by design. */}
      <html
        lang="en"
        suppressHydrationWarning
        className={`${jetbrainsMono.variable} ${instrumentSans.variable} h-full antialiased`}
      >
        <head>
          <script dangerouslySetInnerHTML={{ __html: THEME_BOOT_SCRIPT }} />
        </head>
        <body className="min-h-full flex flex-col bg-canvas text-ink">
          <a
            href="#main"
            className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-accent focus:px-4 focus:py-2 focus:text-sm focus:font-medium focus:text-on-accent"
          >
            Skip to content
          </a>
          <div id="main" className="contents">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
